src/Hoteland/Host/Controllers/FeatureController.cs
using Hoteland.Application.Contract.FeatureAgg;
using Hoteland.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace Host.Controllers
{
    public class FeatureController : Controller
	{
		private readonly IFeatureServices _featureServices;
		private readonly IWebHostEnvironment _hostingEnvironment;
		public FeatureController(IFeatureServices featureServices, IWebHostEnvironment hostingEnvironment)
		{
			_featureServices = featureServices;
			_hostingEnvironment = hostingEnvironment;
		}
		[Route("Feature")]
		public IActionResult Index()
		{
			var features = _featureServices.GetFeatures();
			return View(features);
		}
		[HttpGet]
        [Route("/Create")]
        public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
        [Route("/Create")]

        public IActionResult Create(FeatureDto feature)
		{
			
			if (feature.Picture != null)
			{
				var uploadFolder = Path.Combine(_hostingEnvironment.WebRootPath, "images", "Features");
				if (!Directory.Exists(uploadFolder))
					Directory.CreateDirectory(uploadFolder);
				var fileName = $"{Guid.NewGuid()}-{feature.Picture.FileName}";
				var filePath = Path.Combine(uploadFolder, fileName);
				feature.Picture.CopyTo(new FileStream(filePath, FileMode.Create));
				_featureServices.Insert(feature.Name, $"Features\\{fileName}");
			}

			return RedirectToAction("Index");
				
		}
		[HttpGet]
        [Route("/Update")]
        public IActionResult Update(long ID)
		{
			var feature = _featureServices.GetFeatureByID(ID);
			return View(feature);
		}
		[HttpPost]
        [Route("/Update")]
        public IActionResult Update(FeatureDto feature)
		{
			if (feature.Picture != null)
			{
				var uploadFolder = Path.Combine(_hostingEnvironment.WebRootPath, "images", "Features");
				if (!Directory.Exists(uploadFolder))
					Directory.CreateDirectory(uploadFolder);
				var fileName = $"{Guid.NewGuid()}-{feature.Picture.FileName}";
				var filePath = Path.Combine(uploadFolder, fileName);
				feature.Picture.CopyTo(new FileStream(filePath, FileMode.Create));
				_featureServices.Update(feature.Name, $"Features\\{fileName}",feature.ID);
			}

			return RedirectToAction("Index");
		}
        [Route("/Remove")]
        public IActionResult Remove(long ID)
		{
			_featureServices.Remove(ID);
            return RedirectToAction("Index");
        }

    }
}

src/Hoteland/Host/Controllers/HotelController.cs
using Hoteland.Application.Contract.FeatureAgg;
using Hoteland.Application.Contract.Hotel;
using Hoteland.Application.Contract.Place;
using Hoteland.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace Host.Controllers
{
    public class HotelController : Controller
    {
        private readonly IHotelService _hotelService;
        private readonly ICityService _cityService;
        private readonly ICountryService _countryService;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public HotelController(IHotelService hotelService,
            ICityService cityService, ICountryService countryService, IWebHostEnvironment hostingEnvironment)
        {
            _hotelService = hotelService;
            _cityService = cityService;
            _countryService = countryService;
            _hostingEnvironment = hostingEnvironment;
        }
        [Route("Hotel")]
        [Route("")]
        public IActionResult Index()
        {
            var hotels = _hotelService.GetAllHotels();
            return View(hotels);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var countries = _countryService.GetCountries();
            var cities = _cityService.GetCities();
            var hotelDto = new HotelDto();
            hotelDto.Countries = countries;
            hotelDto.Cities = cities;
            hotelDto.Features = new List<FeatureDto>();
            hotelDto.Pictures = new List<PictureDto>();
            return View(hotelDto);
        }
        [HttpPost]
        public IActionResult Create(HotelDto hotelDto)
        {
            if (hotelDto.Picture != null)
            {
                var uploadFolder = Path.Combine(_hostingEnvironment.WebRootPath, "images", "Hotels");
                if (!Directory.Exists(uploadFolder))
                    Directory.CreateDirectory(uploadFolder);
                var fileName = $"{Guid.NewGuid()}-{hotelDto.Picture.FileName}";
                var filePath = Path.Combine(uploadFolder, fileName);
                hotelDto.Picture.CopyTo(new FileStream(filePath, FileMode.Create));
                hotelDto.Pictures = new List<PictureDto>();
                hotelDto.Features=new List<FeatureDto>();
                _hotelService.InsertHotel(hotelDto, $"Hotels\\{fileName}");
            }
            return RedirectToAction("Index");
        }
        public IList<CityDto> FilterCitiesByCountry(object countryId)
        {
            var cities = _cityService.GetCitiesByCountryID((long)countryId);
            return cities;
        }

    }
}

src/Hoteland/Host/Controllers/PlaceController.cs
using Hoteland.Application.Contract.Place;
using Hoteland.Application.PlaceAgg;
using Microsoft.AspNetCore.Mvc;

namespace Host.Controllers
{
    public class PlaceController : Controller
    {
        private readonly ICountryService _countryService;
        private readonly ICityService _cityService;
        public PlaceController(ICountryService countryService, ICityService cityService)
        {
            _countryService = countryService;
            _cityService = cityService;
        }
        [Route("/GetCountries")]
        public IActionResult GetCountries()
        
        {
            var countries = _countryService.GetCountries();
            return View("CountryIndex",countries);
        }
        [HttpGet]
        [Route("/CreateCountry")]

        public IActionResult CreateCountry()
        {
            return View();
        }
        [HttpPost]
        [Route("/CreateCountry")]
        public IActionResult CreateCountry(CountryDto country)
        {
            _countryService.Insert(country.Name);
           return RedirectToAction("GetCountries");
        }

        [HttpGet]
        [Route("/UpdateCountry")]
        public IActionResult UpdateCountry(long ID)
        {
            var country = _countryService.GetCountryByID(ID);
            return View(country);
        }
        [HttpPost]
        [Route("/UpdateCountry")]
        public IActionResult UpdateCountry(CountryDto country)
        {
            _countryService.Update(country.Name , country.ID);
            return RedirectToAction("GetCountries");
        }
       
        [Route("/RemoveCountry")]
        public IActionResult RemoveCountry(long ID)
        {
            _countryService.Remove(ID);
            return RedirectToAction("GetCountries");
        }

        [Route("/GetCities")]
        public IActionResult GetCities()
        {
            var cities = _cityService.GetCities();
            return View("CityIndex", cities);
        }
        [HttpGet]
        [Route("/CreateCity")]

        public IActionResult CreateCity()
        {
            var countries = _countryService.GetCountries();
            var cityDto = new CityDto();
            cityDto.Countries = countries;
            return View(cityDto);
        }
        [HttpPost]
        [Route("/CreateCity")]
        public IActionResult CreateCity(CityDto city)
        {
            _cityService.Insert(city.Name,city.CountryID);
            return RedirectToAction("GetCities");
        }

        [HttpGet]
        [Route("/UpdateCity")]
        public IActionResult UpdateCity(long ID)
        {
            var city = _cityService.GetCityByID(ID);
            var countries = _countryService.GetCountries();
            city.Countries = countries;
            return View(city);
        }
        [HttpPost]
        [Route("/UpdateCity")]
        public IActionResult UpdateCity(CityDto city)
        {
            _cityService.Update(city);
            return RedirectToAction("GetCities");
        }
        [Route("/RemoveCity")]
        public IActionResult RemoveCity(long ID)
        {
            _cityService.Remove(ID);
            return RedirectToAction("GetCities");
        }
    }
}

src/Hoteland/Host/Views/Feature/Create.cshtml
@model Hoteland.Application.Contract.FeatureAgg.FeatureDto 
<div class="row">
	<div class="col-lg-12 animatedParent animateOnce z-index-47">
		<div class="panel panel-default animated fadeInUp">
			<div class="panel-body">
				<form class="form-horizontal" asp-controller="Feature" asp-action="Create" enctype="multipart/form-data">
					<div class="form-group">
						<label class="col-sm-2 control-label">نام</label>
						<div class="col-sm-10">
							<input type="text" placeholder="لطفا نام امکانات را وارد نمایید " class="form-control" asp-for="Name">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">آیکون</label>
						<div class="col-sm-10">
							<input type="file" class="form-control" asp-for="Picture" accept="image/*">
						</div>
					</div>
					<button type="submit" class="btn btn-success">ذخیره</button>
				</form>
			</div>
		</div>
	</div>
</div>

src/Hoteland/Host/Views/Feature/Index.cshtml
@model IList<Hoteland.Application.Contract.FeatureAgg.FeatureDto>
<div class="header-secondary row gray-bg">
    <div class="col-lg-12">
        <div class="page-heading clearfix">
            <a class="btn btn-primary btn-sm btn-add" asp-controller="Feature" asp-action="Create">اضافه کردن امکانات جدید</a>
        </div>
        <!-- Breadcrumb -->
        <ol class="breadcrumb breadcrumb-2">
            <li><a href="index-2.html"><i class="fa fa-home"></i> داشبورد</a></li>
            <li class="active"><strong>امکانات</strong></li>
        </ol>
        <div class="tab-wrapper clearfix">
            <ul class="nav nav-pills nav-pills-default pull-left">
                <li role="presentation"><a href="simple-view.html">STYLE 1</a></li>
                <li role="presentation"><a href="cards-view.html">STYLE 2</a></li>
                <li role="presentation"><a href="strip-view.html">STYLE 3</a></li>
                <li class="active" role="presentation"><a href="table-view.html">STYLE 4</a></li>
            </ul>
            <ul class="nav nav-pills nav-icons pull-right">
                <li role="presentation"><a href="#"><i class="icon-layout"></i></a></li>
                <li class="active" role="presentation"><a href="#"><i class="icon-list"></i></a></li>
                <li role="presentation"><a href="#" class="toggle-filter" data-block-id="filter-box"><i class="fa fa-filter"></i></a></li>
            </ul>
        </div>
    </div>
</div>
<div class="row datatable-wrapper form-inline">
    <div class="col-lg-12">
        <div class="data-col-first clearfix">
            <div class="col-checkbox col-space">
                <div class="form-checkbox">
                    <input type="checkbox" value="" name=""> <span class="check"><i class="fa fa-check"></i></span>
                </div>
            </div>
            <div class="col-selectbox">
                <select class="form-control input-sm">
                    <option>Bulk Action</option>
                    <option>Bulk Action</option>
                    <option>Bulk Action</option>
                </select>&nbsp;
                <button class="btn btn-primary btn-sm">Go</button>
            </div>
        </div>
        <div class="data-col-last clearfix">
            <div class="col-selectbox">
                <select class="form-control input-sm">
                    <option>Sort By</option>
                    <option>Sort By</option>
                    <option>Sort By</option>
                </select>
            </div>
            <div class="col-selectbox">
                <select class="form-control input-sm">
                    <option>25 Records</option>
                    <option>10 Records</option>
                    <option>50 Records</option>
                </select>
            </div>
        </div>
    </div>
</div>
<div class="animatedParent animateOnce z-index-50">
    <div class="table-responsive animated fadeInUp">
        <table class="table table-users table-hover">
            <thead>
                <tr>
                    <th class="size-60"></th>
                    <th>نام</th>
                    <th class="size-80">آیکون</th>

                    <th class="text-centersize-80">فعالیت ها</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="size-60"><div class="form-checkbox"><input type="checkbox" name="name1" value=""> <span class="check"><i class="fa fa-check"></i></span></div></td>
                        <td><strong>@item.Name</strong></td>
                        <td class="size-80"><img class="avatar img-circle" src="~/images//@item.PicturePath" alt="" title=""></td>
                        <td class="size-80">
                            <a asp-controller="Feature" asp-action="Update" class="btn btn-info" asp-route-id="@item.ID">ویرایش</a>
                            <a asp-controller="Feature" asp-action="Remove" class="btn btn-danger" asp-route-id="@item.ID">حذف</a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

src/Hoteland/Host/Views/Feature/Update.cshtml
@model Hoteland.Application.Contract.FeatureAgg.FeatureDto 
<div class="row">
    <div class="col-lg-12 animatedParent animateOnce z-index-47">
        <div class="panel panel-default animated fadeInUp">
            <div class="panel-body">
                <form class="form-horizontal" asp-controller="Feature" asp-action="Create" enctype="multipart/form-data">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">نام</label>
                        <div class="col-sm-10">
                            <input type="text" placeholder="لطفا نام امکانات را انتخاب نمایید" class="form-control" asp-for="Name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">آیکون امکانات</label>
                        <div class="col-sm-10">
                            <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success">ذخیره</button>
                    <input type="hidden" asp-for="ID" value="@Model.ID"/>
                </form>
            </div>
        </div>
    </div>
</div>

src/Hoteland/Host/Views/Hotel/Create.cshtml
@model Hoteland.Application.Contract.Hotel.HotelDto

<div class="row">
    <div class="col-lg-12 animatedParent animateOnce z-index-47">
        <div class="panel panel-default animated fadeInUp">
            <div class="panel-body">
                <form class="form-horizontal" asp-controller="Hotel" asp-action="Create" enctype="multipart/form-data">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">نام</label>
                        <div class="col-sm-10">
                            <input type="text" placeholder="لطفا نام هتل را وارد نمایید " class="form-control" asp-for="Name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">آدرس</label>
                        <div class="col-sm-10">
                            <input type="text" placeholder="لطفا آدرس را وارد نمایید " class="form-control" asp-for="Address">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">تلفن</label>
                        <div class="col-sm-10">
                            <input type="text"  placeholder="لطفا تلفن هتل را وارد نمایید " class="form-control" asp-for="Tell">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">کشور</label>
                        <div class="col-sm-10">
                            <select id="country" class="select2 form-control"  asp-for="CountryID" asp-items="@(new SelectList(Model.Countries, nameof(Hoteland.Application.Contract.Place.CountryDto.ID), nameof(Hoteland.Application.Contract.Place.CountryDto.Name)))">
                                <option value="0">کشور را انتخاب نمایید</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">شهر</label>
                        <div class="col-sm-10">
                            <select id="city" class="select2 form-control" asp-for="CityID" asp-items="@(new SelectList(Model.Cities, nameof(Hoteland.Application.Contract.Place.CityDto.ID), nameof(Hoteland.Application.Contract.Place.CityDto.Name)))">
                                <option value="0">شهر را انتخاب نمایید</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">تصویر اصلی</label>
                        <div class="col-sm-10">
                            <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">alt تصویر</label>
                        <div class="col-sm-10">
                            <input type="text" placeholder="لطفا alt تصویر هتل را وارد نمایید " class="form-control" asp-for="PictureAlt">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">عنوان تصویر</label>
                        <div class="col-sm-10">
                            <input type="text" placeholder="لطفا عنوان تصویر هتل را وارد نمایید " class="form-control" asp-for="PictureTitle">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">توضیحات</label>
                        <div class="col-sm-10">
                            <input type="text" placeholder="لطفا توضیحات هتل را وارد نمایید " class="form-control" asp-for="Description">
                        </div>
                    </div>
                   
                    <button type="submit" class="btn btn-success">ذخیره</button>
                  
                </form>
            </div>
        </div>
    </div>
</div>

src/Hoteland/Host/Views/Place/CityIndex.cshtml
@model IList<Hoteland.Application.Contract.Place.CityDto>
<div class="header-secondary row gray-bg">
    <div class="col-lg-12">
        <div class="page-heading clearfix">
            <a class="btn btn-primary btn-sm btn-add" asp-controller="Place" asp-action="CreateCity">اضافه کردن شهر جدید</a>
        </div>
        <!-- Breadcrumb -->
        <ol class="breadcrumb breadcrumb-2">
            <li><a href="index-2.html"><i class="fa fa-home"></i> داشبورد</a></li>
            <li class="active"><strong>شهر</strong></li>
        </ol>
        <div class="tab-wrapper clearfix">
            <ul class="nav nav-pills nav-pills-default pull-left">
                <li role="presentation"><a href="simple-view.html">STYLE 1</a></li>
                <li role="presentation"><a href="cards-view.html">STYLE 2</a></li>
                <li role="presentation"><a href="strip-view.html">STYLE 3</a></li>
                <li class="active" role="presentation"><a href="table-view.html">STYLE 4</a></li>
            </ul>
            <ul class="nav nav-pills nav-icons pull-right">
                <li role="presentation"><a href="#"><i class="icon-layout"></i></a></li>
                <li class="active" role="presentation"><a href="#"><i class="icon-list"></i></a></li>
                <li role="presentation"><a href="#" class="toggle-filter" data-block-id="filter-box"><i class="fa fa-filter"></i></a></li>
            </ul>
        </div>
    </div>
</div>
<div class="row datatable-wrapper form-inline">
    <div class="col-lg-12">
        <div class="data-col-first clearfix">
            <div class="col-checkbox col-space">
                <div class="form-checkbox">
                    <input type="checkbox" value="" name=""> <span class="check"><i class="fa fa-check"></i></span>
                </div>
            </div>
            <div class="col-selectbox">
                <select class="form-control input-sm">
                    <option>Bulk Action</option>
                    <option>Bulk Action</option>
                    <option>Bulk Action</option>
                </select>&nbsp;
                <button class="btn btn-primary btn-sm">Go</button>
            </div>
        </div>
        <div class="data-col-last clearfix">
            <div class="col-selectbox">
                <select class="form-control input-sm">
                    <option>Sort By</option>
                    <option>Sort By</option>
                    <option>Sort By</option>
                </select>
            </div>
            <div class="col-selectbox">
                <select class="form-control input-sm">
                    <option>25 Records</option>
                    <option>10 Records</option>
                    <option>50 Records</option>
                </select>
            </div>
        </div>
    </div>
</div>
<div class="animatedParent animateOnce z-index-50">
    <div class="table-responsive animated fadeInUp">
        <table class="table table-users table-hover">
            <thead>
                <tr>
                    <th class="size-60"></th>
                    <th>نام</th>
                    <th>کشور</th>
                    <th class="text-centersize-80">فعالیت ها</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="size-60"><div class="form-checkbox"><input type="checkbox" name="name1" value=""> <span class="check"><i class="fa fa-check"></i></span></div></td>
                        <td><strong>@item.Name</strong></td>
                        <td><strong>@item.Country</strong></td>
                        <td class="size-80">
                            <a asp-controller="Place" asp-action="UpdateCity" class="btn btn-info" asp-route-id="@item.ID">ویرایش</a>
                            <a asp-controller="Place" asp-action="RemoveCity" class="btn btn-danger" asp-route-id="@item.ID">حذف</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

src/Hoteland/Host/Views/Place/CountryIndex.cshtml
@model IList<Hoteland.Application.Contract.Place.CountryDto>
<div class="header-secondary row gray-bg">
    <div class="col-lg-12">
        <div class="page-heading clearfix">
            <a class="btn btn-primary btn-sm btn-add" asp-controller="Place" asp-action="CreateCountry">اضافه کردن کشور جدید</a>
        </div>
        <!-- Breadcrumb -->
        <ol class="breadcrumb breadcrumb-2">
            <li><a href="index-2.html"><i class="fa fa-home"></i> داشبورد</a></li>
            <li class="active"><strong>کشور</strong></li>
        </ol>
        <div class="tab-wrapper clearfix">
            <ul class="nav nav-pills nav-pills-default pull-left">
                <li role="presentation"><a href="simple-view.html">STYLE 1</a></li>
                <li role="presentation"><a href="cards-view.html">STYLE 2</a></li>
                <li role="presentation"><a href="strip-view.html">STYLE 3</a></li>
                <li class="active" role="presentation"><a href="table-view.html">STYLE 4</a></li>
            </ul>
            <ul class="nav nav-pills nav-icons pull-right">
                <li role="presentation"><a href="#"><i class="icon-layout"></i></a></li>
                <li class="active" role="presentation"><a href="#"><i class="icon-list"></i></a></li>
                <li role="presentation"><a href="#" class="toggle-filter" data-block-id="filter-box"><i class="fa fa-filter"></i></a></li>
            </ul>
        </div>
    </div>
</div>
<div class="row datatable-wrapper form-inline">
    <div class="col-lg-12">
        <div class="data-col-first clearfix">
            <div class="col-checkbox col-space">
                <div class="form-checkbox">
                    <input type="checkbox" value="" name=""> <span class="check"><i class="fa fa-check"></i></span>
                </div>
            </div>
            <div class="col-selectbox">
                <select class="form-control input-sm">
                    <option>Bulk Action</option>
                    <option>Bulk Action</option>
                    <option>Bulk Action</option>
                </select>&nbsp;
                <button class="btn btn-primary btn-sm">Go</button>
            </div>
        </div>
        <div class="data-col-last clearfix">
            <div class="col-selectbox">
                <select class="form-control input-sm">
                    <option>Sort By</option>
                    <option>Sort By</option>
                    <option>Sort By</option>
                </select>
            </div>
            <div class="col-selectbox">
                <select class="form-control input-sm">
                    <option>25 Records</option>
                    <option>10 Records</option>
                    <option>50 Records</option>
                </select>
            </div>
        </div>
    </div>
</div>
<div class="animatedParent animateOnce z-index-50">
    <div class="table-responsive animated fadeInUp">
        <table class="table table-users table-hover">
            <thead>
                <tr>
                    <th class="size-60"></th>
                    <th>نام</th>

                    <th class="text-centersize-80">فعالیت ها</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="size-60"><div class="form-checkbox"><input type="checkbox" name="name1" value=""> <span class="check"><i class="fa fa-check"></i></span></div></td>
                        <td><strong>@item.Name</strong></td>
                        <td class="size-80">
                            <a asp-controller="Place" asp-action="UpdateCountry" class="btn btn-info" asp-route-id="@item.ID">ویرایش</a>
                            <a asp-controller="Place" asp-action="RemoveCountry" class="btn btn-danger" asp-route-id="@item.ID">حذف</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

src/Hoteland/Host/Views/Place/CreateCity.cshtml
@model Hoteland.Application.Contract.Place.CityDto
	<div class="row">
		<div class="col-lg-12 animatedParent animateOnce z-index-47">
			<div class="panel panel-default animated fadeInUp">
				<div class="panel-body">
					<form class="form-horizontal" asp-controller="Place" asp-action="CreateCity" enctype="multipart/form-data" >
						<div class="form-group">
							<label class="col-sm-2 control-label">نام</label>
							<div class="col-sm-10">
								<input type="text" placeholder="لطفا نام شهر را وارد نمایید " class="form-control" asp-for="Name">
							</div>
						</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">کشور</label>
						<div class="col-sm-10" >
							<select class="select2 form-control" asp-for="CountryID" asp-items="@(new SelectList(Model.Countries, nameof(Hoteland.Application.Contract.Place.CountryDto.ID), nameof(Hoteland.Application.Contract.Place.CountryDto.Name)))">
								<option value="0">کشور را انتخاب نمایید</option>
							</select>
						</div>
					</div>
						<button type="submit" class="btn btn-success">ذخیره</button>
					</form>
				</div>
			</div>
		</div>
	</div>

src/Hoteland/Host/Views/Place/CreateCountry.cshtml
@model Hoteland.Application.Contract.Place.CountryDto
	<div class="row">
		<div class="col-lg-12 animatedParent animateOnce z-index-47">
			<div class="panel panel-default animated fadeInUp">
				<div class="panel-body">
					<form class="form-horizontal" asp-controller="Place" asp-action="CreateCountry" enctype="multipart/form-data" >
						<div class="form-group">
							<label class="col-sm-2 control-label">نام</label>
							<div class="col-sm-10">
								<input type="text" placeholder="لطفا نام کشور را وارد نمایید :" class="form-control" asp-for="Name">
							</div>
						</div>
						<button type="submit" class="btn btn-success">ذخیره</button>
					</form>
				</div>
			</div>
		</div>
	</div>

src/Hoteland/Host/Views/Place/UpdateCity.cshtml
@model Hoteland.Application.Contract.Place.CityDto
<div class="row">
	<div class="col-lg-12 animatedParent animateOnce z-index-47">
		<div class="panel panel-default animated fadeInUp">
			<div class="panel-body">
				<form class="form-horizontal" asp-controller="Place" asp-action="UpdateCity" enctype="multipart/form-data">
					<div class="form-group">
						<label class="col-sm-2 control-label">نام</label>
						<div class="col-sm-10">
							<input type="text" placeholder="لطفا نام شهر را وارد نمایید " class="form-control" asp-for="Name" value="@Model.Name">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">کشور</label>
						<div class="col-sm-10">
							<select class="select2 form-control" asp-for="CountryID" asp-items="@(new SelectList(Model.Countries, nameof(Hoteland.Application.Contract.Place.CountryDto.ID), nameof(Hoteland.Application.Contract.Place.CountryDto.Name)))">
							</select>
						</div>
					</div>
					<input type="hidden" asp-for="ID" value="@Model.ID"/>
					<button type="submit" class="btn btn-success">ذخیره</button>
				</form>
			</div>
		</div>
	</div>
</div>

src/Hoteland/Host/Views/Place/UpdateCountry.cshtml
@model Hoteland.Application.Contract.Place.CountryDto
<div class="row">
	<div class="col-lg-12 animatedParent animateOnce z-index-47">
		<div class="panel panel-default animated fadeInUp">
			<div class="panel-body">
				<form class="form-horizontal" asp-controller="Place" asp-action="UpdateCountry" enctype="multipart/form-data">
					<div class="form-group">
						<label class="col-sm-2 control-label">نام</label>
						<div class="col-sm-10">
							<input type="text" placeholder="لطفا نام کشور را وارد نمایید :" class="form-control" asp-for="Name" value="@Model.Name">
						</div>
					</div>
					<input type="hidden" asp-for="ID" value="@Model.ID"/>
					<button type="submit" class="btn btn-success">ذخیره</button>
				</form>
			</div>
		</div>
	</div>
</div>